/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankadvanceddb;

import static bankadvanceddb.AdminWindow.DB_URL;
import static bankadvanceddb.AdminWindow.DB_LOGIN;
import static bankadvanceddb.AdminWindow.DB_PASS;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Anton
 */
public class NewKontWindow extends javax.swing.JFrame {


    private int idUs = -1;
    private AdminWindow backWind;
    private boolean kLineEnabled = false;
    private boolean allCorrect = false;
    /**
     * Creates new form NewKontWindow
     * @param id  lietotaja identifikators
     */
    
    public NewKontWindow(int id, AdminWindow ad) {
        initComponents();
        backWind = ad;
        idUs = id;
        krLinePanel.setVisible(false);
        
    }

    public NewKontWindow(int id, AdminWindow ad, String s){

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewKontWindow(id, ad).setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wichKont = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        kontCrAtl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        krLinePanel = new javax.swing.JPanel();
        krLinija = new javax.swing.JTextField();
        krProcenti = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wichKont.add(jRadioButton1);
        jRadioButton1.setText("Kreditu konts");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        wichKont.add(jRadioButton2);
        jRadioButton2.setText("Noreķinu konts");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        kontCrAtl.setText("0");

        jLabel1.setText("Atlikums(0 pec noklusejuma)");

        jLabel2.setText("$");

        krLinePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        krLinija.setText("0");

        krProcenti.setText("0");

        jLabel3.setText("Kreditlinija");

        jLabel4.setText("Procenti");

        javax.swing.GroupLayout krLinePanelLayout = new javax.swing.GroupLayout(krLinePanel);
        krLinePanel.setLayout(krLinePanelLayout);
        krLinePanelLayout.setHorizontalGroup(
            krLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(krLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(krLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(krLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(krLinija, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krProcenti, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        krLinePanelLayout.setVerticalGroup(
            krLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(krLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(krLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(krLinija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(krLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(krProcenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kontCrAtl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addComponent(krLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kontCrAtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(krLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isCorrectValue(String str){
        System.out.println(str);
        try{
            float ft = Float.valueOf(str);
            System.out.print("THIS FLOAT " + ft );
            return true;
        }catch(Exception e){
            return false;
        }
        
        
    }
            
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(((kontCrAtl.getText().length() == 0 ) || (kontCrAtl.getText().length() < 9))  && (isCorrectValue(kontCrAtl.getText()))   ){
            
            try{
                        
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection(DB_URL,DB_LOGIN, DB_PASS);
                    Statement st = con.createStatement();  
                     
                    if(jRadioButton1.isSelected()){
                        System.out.println("Kreditu konts");
                        
                        
                        backWind.setVisible(true);
                        if(isCorrectValue(krLinija.getText()) && isCorrectValue(krProcenti.getText()) ){
                            if((Float.parseFloat(krLinija.getText()) < 10000.00) && (Float.parseFloat(krLinija.getText()) > 0 )
                                    && (Float.parseFloat(krProcenti.getText()) > 0) && (Float.parseFloat(krProcenti.getText()) < 50)){
                                
                                
                                Random rd = new Random();
                                String kNum = Integer.toString((rd.nextInt(899)+100))   +  Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(10));
                                System.out.println(idUs);
                                
                                String sql = "INSERT INTO KredKonti (id, kNum, kr, krAtlikums, procenti) VALUES("+ idUs + ", '" + kNum +"', " + Float.parseFloat(krLinija.getText()) + ", " + Float.parseFloat(kontCrAtl.getText())+  ", " + Float.parseFloat(krProcenti.getText()) + ")";
                                System.out.println(sql);
                                
                                st.executeUpdate(sql);
                                //DESTROY
                                allCorrect = true;
                                backWind.dispose();
                            }
                        }

                    }else{
                        if(jRadioButton2.isSelected()){
                            System.out.println("Norekinu konts");
                            
                            
                
                            Random rd = new Random();
                            String kNum = Integer.toString((rd.nextInt(899)+100))   +  Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(10));
                            String sql1 = "INSERT INTO NorekKonti (id, kNum, atlikums) VALUES(" + idUs + ", " + "'" +kNum  + "', " + Float.parseFloat(kontCrAtl.getText()) + ")";
                            
                            System.out.println(sql1);
                            st.executeUpdate(sql1);
                            backWind.dispose();
                            allCorrect = true;
                            //DESTTORY
                        }else{
                            allCorrect = false;
                            JOptionPane.showMessageDialog(this," Ir jaizvelas, kuru kontu jus gribat izveidot (kredit vai noreķinu)", "Kluda", JOptionPane.ERROR_MESSAGE);
                        }
                   
               
                    }
                    
                    //buttons back pressed
                    if(allCorrect ){
                        st.close();
                        con.close();
                        this.dispose();
                        AdminWindow ad = new AdminWindow(1);  
                        //ad.setVisible(true);
                    }
                    
                    
                }catch(SQLException ex){
                    ex.printStackTrace();
                }catch(Exception e){
                    e.printStackTrace();
                }finally{
                        
                }
                    
                    
            
            
        }else{
            JOptionPane.showMessageDialog(this," Jusu ievaditaja atlikuma ir nekorekts formats", "Kluda", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        
            
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
    }//GEN-LAST:event_formMouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        if(jRadioButton1.isSelected()){
            krLinePanel.setVisible(true);
            
        }
        else krLinePanel.setVisible(false);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
       if(jRadioButton1.isSelected()){
            krLinePanel.setVisible(true);
            
        }
        else krLinePanel.setVisible(false);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        backWind.setVisible(true);  //BACK BUTTONS
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField kontCrAtl;
    private javax.swing.JPanel krLinePanel;
    private javax.swing.JTextField krLinija;
    private javax.swing.JTextField krProcenti;
    private javax.swing.ButtonGroup wichKont;
    // End of variables declaration//GEN-END:variables
}
