/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankadvanceddb;

import static bankadvanceddb.AdminWindow.DB_URL;
import static bankadvanceddb.AdminWindow.DB_LOGIN;
import static bankadvanceddb.AdminWindow.DB_PASS;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Anton
 */
public class NorKontWindow extends javax.swing.JFrame {

    private String defKnum = "";
    private float defAtl = 0;
    /**
     * Creates new form NorKontWindow
     */
    public NorKontWindow(String knum, float atlikums) {
        initComponents();
        defKnum = knum;
        defAtl = atlikums;
        
        kNumF.setText(knum);
        atlF.setText(Float.toString(atlikums));
        loadNum.setText(knum);
        
        
    }

    public NorKontWindow(String knum, float atlikums,String type){
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NorKontWindow(knum,atlikums).setVisible(true);
            }
        });
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kNumF = new javax.swing.JTextField();
        atlF = new javax.swing.JTextField();
        sgIzm = new javax.swing.JButton();
        gnr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loadNum = new javax.swing.JLabel();
        backButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        kNumF.setEditable(false);

        atlF.setText("0");

        sgIzm.setText("Saglabat ");
        sgIzm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgIzmActionPerformed(evt);
            }
        });

        gnr.setText("Ģeneret");
        gnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnrActionPerformed(evt);
            }
        });

        jLabel1.setText("Konta numurs");

        jLabel2.setText("Konta atlikums");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kNumF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(gnr))
                    .addComponent(atlF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sgIzm)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kNumF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gnr)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atlF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(sgIzm)
                .addContainerGap())
        );

        loadNum.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        backButt.setText("Back");
        backButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadNum)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(loadNum)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButt)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkForFloat(String str){
        
        try{
            Float.parseFloat(str);
            return true;
        }catch(Exception e){
            return false;
        }
        
    }
    
    private void sgIzmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgIzmActionPerformed
        if(checkForFloat(atlF.getText())    &&  (atlF.getText().length()!=0 )){
            if( Float.parseFloat(atlF.getText()) > 0  ){
                try{
                    
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection(DB_URL,DB_LOGIN, DB_PASS);
                    
                    PreparedStatement st = con.prepareStatement("UPDATE NorekKonti SET kNum = ?, atlikums ? WHERE kNum = ?");
                    st.setString(1, kNumF.getText());
                    st.setFloat(2, Float.parseFloat(atlF.getText()));
                    st.setString(3, defKnum);
                    
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Izmaiņas tika saglabatas");
                    this.dispose();
                    
                
                    
                }catch(SQLException ex){
                    ex.printStackTrace();
                    
                }catch(Exception e){
                    e.printStackTrace();
                }finally{
                    
                }
                
                
                
                
                
            }else JOptionPane.showMessageDialog(this, "Nav iespejams uzstadit negativo atlikumu");   
        }else JOptionPane.showMessageDialog(this, "Ir jaievada skaitli");
    }//GEN-LAST:event_sgIzmActionPerformed

    private void gnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnrActionPerformed
        Random rd = new Random();
        String kNum = Integer.toString((rd.nextInt(899)+100))   +  Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(899)+100) + Integer.toString(rd.nextInt(10));
        kNumF.setText(kNum);
    }//GEN-LAST:event_gnrActionPerformed

    private void backButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atlF;
    private javax.swing.JButton backButt;
    private javax.swing.JButton gnr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kNumF;
    private javax.swing.JLabel loadNum;
    private javax.swing.JButton sgIzm;
    // End of variables declaration//GEN-END:variables
}
