/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankadvanceddb;

import static bankadvanceddb.AdminWindow.DB_URL;
import static bankadvanceddb.AdminWindow.DB_LOGIN;
import static bankadvanceddb.AdminWindow.DB_PASS;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author Anton
 */
public class RegisterForm extends javax.swing.JFrame {
    
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    
    
    private  int[] D_IN_MONTH = {31,28,31,30,31,30,31,30,31,30,31,30}; //NOT VISKOC
    
    private String userLogin;
    private String userName;
    private String userSurname;
    private int bYear;
    private int bMonth;
    private int bDay;
    private String pilseta;
    private String pass;
    private java.util.Date datums;
    private Date registrationDate;
    private AdminWindow backToAdm;
    /**
     * Creates new form RegisterForm
     */
    public RegisterForm(AdminWindow adm) {
        initComponents();
        backToAdm = adm;
    }
    
    public RegisterForm(int i,AdminWindow adm){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm(adm).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        userRegisterName = new javax.swing.JTextField();
        userRegisterSurname = new javax.swing.JTextField();
        userRegisterBYear = new javax.swing.JTextField();
        userRegisterMonth = new javax.swing.JTextField();
        userRegsterDay = new javax.swing.JTextField();
        jPilsetas = new javax.swing.JComboBox<>();
        TextFieldDate = new javax.swing.JTextField();
        RegisterNextStep = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userRegisterPass = new javax.swing.JPasswordField();
        userRegisterPassRepeat = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setLocation(new java.awt.Point(700, 400));
        jDialog1.setName("izveidesLogs"); // NOI18N
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(250, 150));

        jButton2.setText("Paldies!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Jauns lietotajs tika izveidots");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(53, 53, 53))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPilsetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ainazi", "Aizkraukle", "Aizpute", "Akniste", "Aloja", "Ape", "Auce", "Baldone", "Balozi", "Balvi", "Bauska", "Broceni", "Cesis", "Cesvaine", "Dagda", "Daugavpils", "Dobele", "Durbe", "Grobina", "Gulbene", "Ikskile", "Ilukste", "Jaunjelgava", "Jekabpils", "Jelgava", "Jurmala", "Kandava", "Karsava", "Kegums", "Kraslava", "Kuldiga", "Lielvarde", "Liepaja", "Ligatne", "Limbazi", "Livani", "Lubāna", "Ludza", "Madona", "Mazsalaca", "Ogre", "Olaine", "Pavilosta", "Piltene", "Plavinas", "Preili", "Priekule", "Rezekne", "Riga", "Rujiena", "Sabile", "Salacgriva", "Salaspils", "Saldus", "Saulkrasti", "Seda", "Sigulda", "Skrunda", "Smiltene", "Staicele", "Stende", "Strenci", "Subate", "Talsi", "Tukums", "Valdemarpils", "Valka", "Valmiera", "Vangazi", "Varaklani", "Ventspils", "Viesite", "Vilaka", "Vilani", "Zilupe" }));

        TextFieldDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldDateKeyTyped(evt);
            }
        });

        RegisterNextStep.setText("Next");
        RegisterNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterNextStepActionPerformed(evt);
            }
        });

        jLabel2.setText("Vards");

        jLabel3.setText("Uzvards");

        jLabel4.setText("Dz.gads");

        jLabel5.setText("Dz.menesis");

        jLabel6.setText("Dz.diena");

        jLabel7.setText("Jauna parole");

        jLabel8.setText("Velreiz parole");

        jLabel9.setText("Izveleties pilsetu");

        jLabel10.setText("Reģistracijas datums ");

        jLabel12.setText("(yyyy-MM-dd) (manuali)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userRegisterMonth)
                                        .addComponent(userRegsterDay)
                                        .addComponent(userRegisterBYear)
                                        .addComponent(userRegisterSurname)
                                        .addComponent(userRegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(userRegisterPass, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jPilsetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterNextStep, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(userRegisterPassRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(180, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(26, 26, 26))
                                .addComponent(jLabel5))
                            .addGap(82, 82, 82))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jPilsetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addGap(74, 74, 74)
                            .addComponent(jLabel6)
                            .addGap(49, 49, 49)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userRegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userRegisterSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userRegisterBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userRegisterMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userRegsterDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userRegisterPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(userRegisterPassRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(RegisterNextStep)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("New User Register");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(290, 290, 290))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(58, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterNextStepActionPerformed
        
        try{
            
           String regDate = TextFieldDate.getText();
           SimpleDateFormat tForm = new SimpleDateFormat("yyyy-MM-dd");
           registrationDate = tForm.parse(regDate); 
            
        }catch(ParseException e){
            e.printStackTrace();
        }
        
          // TextFieldDate.setToolTipText("Ievadiet pareizo datumus formata"); 
        //REG WINDOWS COMPONENT INIT
        userLogin = userRegisterName.getText() + "." + userRegisterSurname.getText();
        System.out.println(userLogin);
        System.out.print("Registracija piekrita");
        bYear = Integer.parseInt(userRegisterBYear.getText());
        bMonth = Integer.parseInt(userRegisterMonth.getText());
        bDay = Integer.parseInt(userRegsterDay.getText());
        
        String bDate = Integer.toString(bYear) + "-" + Integer.toString(bMonth) + "-" + Integer.toString(bDay) ;
        pilseta = jPilsetas.getSelectedItem().toString();
        System.out.print(pilseta);
        String userPass = String.valueOf(userRegisterPass.getPassword());
        String userPassRep = String.valueOf(userRegisterPassRepeat.getPassword());
        
        try{
            
                    System.out.println("CONNECTING TO DB");
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection(DB_URL,DB_LOGIN, DB_PASS);
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("SELECT * from Users where login = '" + userLogin + "'");
                    
                    if(!rs.next())
                    {

                        //regiDateConvertTODBFORMAT
                        Calendar tempCal = Calendar.getInstance();
                        tempCal.setTime(registrationDate);
                        String registrationDateStr = Integer.toString(tempCal.get(Calendar.YEAR)) + "-" + Integer.toString(tempCal.get(Calendar.MONTH)) + "-" + Integer.toString(tempCal.get(Calendar.DAY_OF_MONTH));
                        SimpleDateFormat sql = new SimpleDateFormat("yyyy-MM-dd");
                        registrationDate = sql.parse(registrationDateStr);
                        System.out.println(registrationDate + "registrationDate");
                        
                        System.out.println(isValidDate(parseDate(bDate)) + " " + isValidDate(registrationDate));
                        System.out.println(bDate);
                        if(userPass.equals(userPassRep)  && isValidDate(parseDate(bDate)) && (isValidDate(registrationDate) && (userPass.length() > 8) && (userRegisterName.getText().length() != 0) && (userRegisterSurname.getText().length() !=0 )))
                        {
                            userName = userRegisterName.getText();
                            userSurname = userRegisterSurname.getText();
                            pass = String.valueOf(userRegisterPass.getPassword());
                           
                            
                            //INSERT TO DB
                            
                            //WINDOWS OF SUCCESS
                            String login = userName.toString() + "." + userSurname.toString();
                            login.toLowerCase();
                            userName = userName.substring(0,1).toUpperCase() + userName.substring(1).toLowerCase();
                            userSurname = userSurname.substring(0,1).toUpperCase() + userSurname.substring(1).toLowerCase();
                            System.out.println(login + " LOGIN");
                            
                            
                            String sqlInsert = "INSERT INTO Users" +
                                    " (id, userFirstname, userLastname, login, pass, bDate, city, regDatums) " +
                                    "VALUES" + "(NULL, " + "'" + userName + "', " + "'" + userSurname + "', "  + "'" + login + "', " + "'" + pass + "', "  + "'" + bDate + "'"+ ", '" + pilseta + "', '" + registrationDateStr + "')"; 
                            System.out.println(sqlInsert);
                            st.executeUpdate(sqlInsert);
                            this.dispose();
                            backToAdm.setVisible(true);
                            jDialog1.setVisible(true);
                        }else{
                            JOptionPane.showMessageDialog(this, "Tika ievaditi nekorekti dati");
                        }
                        
                        
                    }
                    
                    //CLEANING
                    rs.close();
                    st.close();
                    con.close();
                    
                    }catch(SQLException se){
                       se.printStackTrace();
                    }catch(Exception s){
                        s.printStackTrace();
                    }finally{
                        //FIN
                    }
        
        
        
    }//GEN-LAST:event_RegisterNextStepActionPerformed

    public java.util.Date parseDate(String text)   //CUSTOM DATE PARSER
    {
        try{

            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            Date date = s.parse(text);
            return date;
        
        }catch( ParseException e){
            e.printStackTrace();
            
        } 
        return null;
    }
    
    private void TextFieldDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldDateKeyTyped

        // 
    }//GEN-LAST:event_TextFieldDateKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        backToAdm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    //PALIGA^^^^^
    
    
    public boolean isValidDate(java.util.Date date){
        
        
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        int year = cal.get(Calendar.YEAR);
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        if(isVesoc(year)){
            D_IN_MONTH[1] = 29;
        }

        if((year > 1900 && year < 2017) && ( month > 0 && month <= 12 ) && (day > 0 && day < D_IN_MONTH[month-1] ) ){
            
            System.out.println("isvalidDate  True" );
            return true;
        }else {
            System.out.println("isvalidDate False " );
            return false;
        }
            
        
        
    }
    
    private boolean isVesoc(int year){
        if(year % 400 == 0) return true;
        else{
            if (year % 100 != 0)  
                if(year % 4 == 0) return true;
            return false;
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterNextStep;
    private javax.swing.JTextField TextFieldDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jPilsetas;
    private javax.swing.JTextField userRegisterBYear;
    private javax.swing.JTextField userRegisterMonth;
    private javax.swing.JTextField userRegisterName;
    private javax.swing.JPasswordField userRegisterPass;
    private javax.swing.JPasswordField userRegisterPassRepeat;
    private javax.swing.JTextField userRegisterSurname;
    private javax.swing.JTextField userRegsterDay;
    // End of variables declaration//GEN-END:variables
}
